python bin/train_elmo_curriculum.py --save_dir models/curriculumline/103/baseline/ --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens --target_batches 12000 --test_interval 100 --initial_competence 1.0 > Results/curriculumline/103/baselinetrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/103/pos --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.pos_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens --target_batches 12000 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculumline/103/postrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/103/dep --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.dep_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens --target_batches 12000 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculumline/103/deptrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/103/len --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.len_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens --target_batches 12000 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculumline/103/lentrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/103/random --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.random_line --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens --target_batches 12000 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculumline/103/randomtrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/103/trigram --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.trigram_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens --target_batches 12000 --test_interval 100 --initial_competence 0.01 --competence_increment 0.00001 > Results/curriculumline/103/tritrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/103/bigram --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.bigram_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens --target_batches 12000 --test_interval 100 --initial_competence 0.01 --competence_increment 0.00001 > Results/curriculumline/103/bitrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/103/unigram --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.unigram_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens --target_batches 12000 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculumline/103/unitrain.txt

python bin/train_elmo_curriculum.py --save_dir models/curriculum/103/baseline/ --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens.sent --target_batches 18900 --test_interval 100 --initial_competence 1.0 > Results/curriculum/103/baselinetrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/103/pos --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.pos_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens.sent --target_batches 18900 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculum/103/postrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/103/dep --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.dep_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens.sent --target_batches 18900 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculum/103/deptrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/103/len --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.len_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens.sent --target_batches 18900 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculum/103/lentrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/103/random --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.random_line --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens.sent --target_batches 18900 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculum/103/randomtrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/103/trigram --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.trigram_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens.sent --target_batches 18900 --test_interval 100 --initial_competence 0.01 --competence_increment 0.00001 > Results/curriculum/103/tritrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/103/bigram --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.bigram_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens.sent --target_batches 18900 --test_interval 100 --initial_competence 0.01 --competence_increment 0.00001 > Results/curriculum/103/bitrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/103/unigram --vocab_file wikitext-103/vocab.txt --train_prefix wikitext-103/wiki.train.tokens.unigram_line_sort --train_tokens wikitext103 --test_prefix wikitext-103/wiki.valid.tokens.sent --target_batches 18900 --test_interval 100 --initial_competence 0.1 --competence_increment 0.00001 > Results/curriculum/103/unitrain.txt

