python bin/train_elmo_curriculum.py --save_dir models/curriculum/2/baseline/ --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.sent --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens.sent --target_batches 3820 --test_interval 100 --initial_competence 1.0 > Results/curriculum/2/baselinetrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/2/pos --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.pos_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens.sent --target_batches 3820 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculum/2/postrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/2/dep --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.dep_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens.sent --target_batches 3820 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculum/2/deptrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/2/len --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.len_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens.sent --target_batches 3820 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculum/2/lentrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/2/random --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.random --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens.sent --target_batches 3820 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculum/2/randomtrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/2/trigram --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.trigram_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens.sent --target_batches 3820 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculum/2/tritrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/2/bigram --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.bigram_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens.sent --target_batches 3820 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculum/2/bitrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculum/2/unigram --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.unigram_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens.sent --target_batches 3820 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculum/2/unitrain.txt

python bin/train_elmo_curriculum.py --save_dir models/curriculumline/2/baseline/ --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens --target_batches 2400 --test_interval 100 --initial_competence 1.0 > Results/curriculumline/2/baselinetrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/2/pos --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.pos_line_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens --target_batches 2400 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculumline/2/postrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/2/dep --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.dep_line_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens --target_batches 2400 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculumline/2/deptrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/2/len --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.len_line_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens --target_batches 2400 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculumline/2/lentrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/2/random --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.random_line --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens --target_batches 2400 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculumline/2/randomtrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/2/trigram --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.trigram_line_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens --target_batches 2400 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculumline/2/tritrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/2/bigram --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.bigram_line_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens --target_batches 2400 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculumline/2/bitrain.txt
python bin/train_elmo_curriculum.py --save_dir models/curriculumline/2/unigram --vocab_file wikitext-2/vocab.txt --train_prefix wikitext-2/wiki.train.tokens.unigram_line_sort --train_tokens wikitext2 --test_prefix wikitext-2/wiki.valid.tokens --target_batches 2400 --test_interval 100 --initial_competence 0.1 --competence_increment 0.0004 > Results/curriculumline/2/unitrain.txt


